version: '3.8'

networks:
  nbank-network:
    name: nbank-network

services:
  backend:
    image: nobugsme/nbank:with_username_error_fix
    container_name: nbank-backend
    ports:
      - "4111:4111"
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4111/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    image: nobugsme/nbank-ui:latest
    container_name: nbank-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s